name: tictactoe
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  bloc: ^7.0.0
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  #flutter_svg: ^1.1.6
  material_design_icons_flutter: ^5.0.6295
  material_dialogs: ^1.1.1
  quiver: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:

  uses-material-design: true

  assets:
    - img/
    - res/
